//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPdotNET_CUOIMON.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class handbagShopDBEntities : DbContext
    {
        public handbagShopDBEntities()
            : base("name=handbagShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_categories> tbl_categories { get; set; }
        public DbSet<tbl_order_details> tbl_order_details { get; set; }
        public DbSet<tbl_orders> tbl_orders { get; set; }
        public DbSet<tbl_product_images> tbl_product_images { get; set; }
        public DbSet<tbl_products> tbl_products { get; set; }
        public DbSet<tbl_users> tbl_users { get; set; }
    }
}
