//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPdotNET_CUOIMON.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders
    {
        public tbl_orders()
        {
            this.tbl_order_details = new HashSet<tbl_order_details>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string status { get; set; }
        public Nullable<double> quote_price { get; set; }
        public string quote_note { get; set; }
        public Nullable<double> deposit_amount { get; set; }
        public Nullable<System.DateTime> estimated_delivery_date { get; set; }
        public string shipping_address { get; set; }
        public string additional_request { get; set; }
        public string admin_note { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual ICollection<tbl_order_details> tbl_order_details { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
