//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPdotNET_CUOIMON.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order_details
    {
        public int order_detail_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public string custom_note { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual tbl_orders tbl_orders { get; set; }
        public virtual tbl_products tbl_products { get; set; }
    }
}
