//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPdotNET_CUOIMON.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_categories
    {
        public tbl_categories()
        {
            this.tbl_products = new HashSet<tbl_products>();
        }
    
        public int category_id { get; set; }
        public string name { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual ICollection<tbl_products> tbl_products { get; set; }
    }
}
