//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPdotNET_CUOIMON.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product_images
    {
        public int image_id { get; set; }
        public int product_id { get; set; }
        public string image_url { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual tbl_products tbl_products { get; set; }
    }
}
