//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPdotNET_CUOIMON.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public tbl_users()
        {
            this.tbl_orders = new HashSet<tbl_orders>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string password_hash { get; set; }
        public string email { get; set; }
        public string full_name { get; set; }
        public string phone { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual ICollection<tbl_orders> tbl_orders { get; set; }
    }
}
