//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPdotNET_CUOIMON.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        public tbl_products()
        {
            this.tbl_order_details = new HashSet<tbl_order_details>();
            this.tbl_product_images = new HashSet<tbl_product_images>();
        }
    
        public int product_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> category_id { get; set; }
        public string image_url { get; set; }
        public Nullable<bool> is_available { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual tbl_categories tbl_categories { get; set; }
        public virtual ICollection<tbl_order_details> tbl_order_details { get; set; }
        public virtual ICollection<tbl_product_images> tbl_product_images { get; set; }
    }
}
